apiVersion: v1
kind: Service
metadata:
  name: pnote
  namespace: default
spec:
  selector:
    app: pnote
    release: "1"
  ports:
  - name: http
    port: 80 
    targetPort: 1154
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pnote-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pnote
      release: "1"
  template:
    metadata:
      labels:
        app: pnote
        release: "1"
    spec:
      containers:
      - name: pnote
        image: apporoad/pnote:1
        ports:
        - name: aok
          containerPort: 1154